# Variable definitions and descriptions for iMSMS data visualization
# This file contains variable classifications, bin counts, and descriptions

# Define variables that should be treated as discrete
DISCRETE_VARIABLES = {
    'administration', 'allergies', 'allergy_specific', 'anxiety', 'asthma', 
    'birth_method', 'breastfeeding', 'depression', 'diet_no_special_needs', 
    'diet_special_needs', 'disease', 'disease_course', 'disease_course_control', 
    'dmt', 'eating_disorder', 'eczema', 'education', 'ethnicity', 'manic_depression_bipolar', 
    'ms_family', 'nsaids', 'nsaids_specifics', 'occupation', 'ocd', 'ocps_y_n', 
    'otc_meds', 'pets', 'postpartum_depression', 'probiotics', 'recreational_drug', 
    'sex', 'site', 'smoke', 'treated', 'treatment_status', 
    'treatments', 'treatments_control', 'type2diabetes', 'weight_change', 
    'which_ocp'
}

# Define variables that should always be treated as continuous (override other detection)
FORCE_CONTINUOUS = {
    'ADDSUG', 'age', 'Alcohol % of cals (%)', 'B1, B2 (mg)', 'Beta-carotene (mcg)', 'bmi', 
    'Bread, pasta, rice (1)', 'Calcium (mg)','Calories (Kcal)','Carbohydrate (g)', 
    'Carbohydrate (g) as % of cals', 'children_number', 'Cholestrol (mg)', 'csf_results', 
    'Dietary Fiber(g)', 'disease_duration', 'edss', 'FATTYACID', 'Fat (g)', 
    'Fat (g) as % of cals', 'Folate (mcg)', 'Fruits, fruit juices (cups)', 
    'Good oils, in foods ("teaspoons")', 'GREEN_AND_BEAN', 'HEI2015_TOTAL_SCORE', 'height', 
    'Iron (mg)', 'Magnesium (mg)',  'Meat, eggs, or beans (1)', 'Milk, cheese, yogurt (cups)', 
    'Monounsaturated fat (g)', 'MSSS', 'Niacin (mg)', 'otc_number', 'Polyunsaturated fat (g)', 
    'Potassium (mg)', 'Protein (g)', 'Protein (g) as % of cals', 'REFINEDGRAIN', 'relapse_number', 
    'roommates', 'rxmeds', 'rxmeds_number', 'Saturated fat (g)','Saturated fat (g) as % of cals',
    'SEAPLANT_PROT', 'SFA', 'SODIUM', 'Sodium (salt) (mg)', 'spms_year', 'Sweets % of cals (%)', 
    'Vegetables group (cups)', 'Vitamdietpairsumin A (RAE)', 'TOTALDAIRY', 'TOTALFRUIT','TOTALVEG', 
    'TOTPROT', 'Vitamin B6 (mg)', 'Vitamin C (mg)', 'vitamin D (IU)', 'Vitamin E (mg)',  'weight', 
    'WHOLEFRUIT','WHOLEGRAIN', 'Whole grains (1)', 'without potatoes (cups)', 'year_of_onset', 
    'Zinc (mg)',       
}

# Define variable-specific bin counts
VARIABLE_BIN_COUNTS = {
    'ADDSUG':5,
    'administration':5,
    'age': 5,
    'Alcohol % of cals (%)': 4,
    'allergies':3,
    'allergy_specific': 286,
    'anxiety': 3,
    'asthma': 3,
    'B1, B2 (mg)': 5,
    'Beta-carotene (mcg)':5,
    'birth_method':3,
    'bmi': 4,
    'Bread, pasta, rice (1)':5,
    'breastfeeding': 3,
    'Calcium (mg)': 5,
    'Calories (Kcal)': 5,
    'Carbohydrate (g)': 5,
    'Carbohydrate (g) as % of cals': 5,
    'children_number': 5,
    'Cholestrol (mg)': 5,
    'csf_results': 4,
    'depression': 3,
    'diet_no_special_needs': 2,
    'diet_special_needs': 27,
    'Dietary Fiber(g)': 5,
    'disease': 2,
    'disease_course': 4,
    'disease_course_control': 4,
    'disease_duration': 6,
    'dmt': 3,
    'eating_disorder': 3,
    'eczema': 3,
    'edss': 5,
    'education': 6,
    'ethnicity': 4,
    'Fat (g)': 5,
    'Fat (g) as % of cals': 5,
    'FATTYACID': 5,
    'Folate (mcg)': 5,
    'Fruits, fruit juices (cups)': 4,
    'Good oils, in foods ("teaspoons")': 5,
    'GREEN_AND_BEAN': 5,
    'HEI2015_TOTAL_SCORE': 5,
    'height': 4,
    'household': 2,
    'Iron (mg)': 5,
    'Magnesium (mg)': 5,
    'manic_depression_bipolar': 3,
    'Meat, eggs, or beans (1)': 5,
    'Milk, cheese, yogurt (cups)': 5,
    'Monounsaturated fat (g)': 5,
    'ms_family': 3,
    'MSSS': 6,
    'Niacin (mg)': 5,
    'nsaids': 3,
    'nsaids_specifics': 264,
    'occupation': 623,
    'ocd': 3,
    'ocps_y_n': 3,
    'otc_meds': 3,
    'otc_number': 6,
    'pets': 3,
    'Polyunsaturated fat (g)': 5,
    'postpartum_depression': 3,
    'Potassium (mg)': 5,
    'probiotics': 3,
    'Protein (g)': 5,
    'Protein (g) as % of cals': 5,
    'recreational_drug': 3,
    'REFINEDGRAIN': 5,
    'relapse_number': 6,
    'roommates': 3,
    'rxmeds': 4,
    'rxmeds_number': 6,
    'Saturated fat (g)': 5,
    'Saturated fat (g) as % of cals': 5,
    'SEAPLANT_PROT': 5,
    'sex': 2,
    'SFA': 5,
    'site': 7,
    'smoke': 4,
    'SODIUM': 5,
    'Sodium (salt) (mg)': 5,
    'spms_year': 24,
    'Sweets % of cals (%)': 5,
    'TOTALDAIRY': 5,
    'TOTALFRUIT': 5,
    'TOTALVEG': 5,
    'TOTPROT': 5,
    'treated': 4,
    'treatment_status': 3,
    'treatments': 8,
    'treatments_control': 14,
    'type2diabetes': 3,
    'Vegetables group (cups)': 5,
    'Vitamdietpairsumin A (RAE)': 5,
    'Vitamin B6 (mg)': 5,
    'Vitamin C (mg)': 4,
    'vitamin D (IU)': 5,
    'Vitamin E (mg)': 5,
    'weight': 5,
    'weight_change': 3,
    'which_ocp': 45,
    'Whole grains (1)': 5,
    'WHOLEFRUIT': 5,
    'WHOLEGRAIN': 5,
    'without potatoes (cups)': 5,
    'year_of_onset': 53,
    'Zinc (mg)': 5
}

# Variable descriptions for each variable in the dataset
VARIABLE_DESCRIPTIONS = {
    'ADDSUG': 'Added sugar content in diet over 6-12 months. SEE HEI2015 information.',
    'FATTYACID': 'Fatty acid profile in diet over 6-12 months. SEE HEI2015 information.',
    'GREEN_AND_BEAN': 'Dark green vegetables and beans and peas in diet over 6-12 months. SEE HEI2015 information.',
    'TOTALDAIRY': 'Fat free dairy consumption over 6-12 months. SEE HEI2015 information.',
    'TOTALFRUIT': 'Fruit consumption(including fruit juice) over 6-12 months. SEE HEI2015 information.',
    'TOTALVEG': 'Vegetable consumption over 6-12 months. SEE HEI2015 information.',
    'TOTPROT': 'Protein consumption over 6-12 months. SEE HEI2015 information.',
    'HEI2015_TOTAL_SCORE': 'The HEI2015 is the latest iteration of the Healthy Eating Index, a tool designed to measure diet quality—that is, how closely an eating pattern or mix of foods matches the Dietary Guidelines for Americans recommendations. HEI2015 is a total value of ADDSUG, FATTYACID, GREEN_AND_BEAN, TOTALDAIRY, TOTALFRUIT, TOTALVEG, TOTPROT, REFINEDGRAIN, WHOLEFRUIT, WHOLEGRAIN, SFA, SEAPLANT_PROT, SODIUM',
    'REFINEDGRAIN': 'Refined grain consumption over 6-12 months. SEE HEI2015 information.',
    'WHOLEFRUIT': 'Fruit consumption(without fruit juice) over 6-12 months. SEE HEI2015 information.',
    'WHOLEGRAIN': 'Whole grain consumption over 6-12 months. SEE HEI2015 information.',
    'SFA': 'Saturated fat consumption over 6-12 months. SEE HEI2015 information.',
    'SEAPLANT_PROT': 'Protein consumption(seafood + plants) over 6-12 months.SEE HEI2015 information.',
    'SODIUM': 'Sodium consumption over 6-12 months. SEE HEI2015 information.',
    
    'administration': 'How the DMTs were administered to the participant with MS',
    'age': 'What is the participants age',
    'allergies': 'Does participant have an allergy',
    'allergy_specific': 'Participant allergy type',
    'anxiety': 'Does participant have anxiety or not',
    'asthma': 'Does participant have asthma or not',
    'birth_method': 'How was participant born',
    'bmi': 'Participant BMI calculated from height(cm) and weight(kg) measurements',
    'breastfeeding': 'Did participant breastfeed as a child',
    'children_number': 'participant children number',
    'depression': 'Does participant have depression or not',
    'diet_no_special_needs': 'Whether participant has dietary restrictions or not',
    'diet_special_needs': 'Dietary restriction(s) for participant',
    'disease': 'Whether participant has MS or not',
    'disease_course_control': 'MS patient + their controls corresponding pair value. Patient can have RRMS or PMS(SPMS and PPMS lumped together) If MS patient has RRMS, corresponding household member(control) would be control_RRMS. ',
    'disease_duration': 'How long the patient has had MS',
    'dmt': 'Among the 576 MS patients, 209 (36%) were untreated and 367 (63%) were treated with a disease modifying therapy (DMT). Note that this was done before the study. In page 17-18, we see that Participants were excluded if they received oral antibiotics within the past three months, corticosteroids within the past 30 days, or were on a disease modifying therapy for less than three months',
    'eating_disorder': 'Does participant have eating_disorder or not',
    'eczema': 'Does participant have eczema or not',
    'edss': 'The Expanded Disability Status Scale (EDSS) is a tool used to measure disability in people with multiple sclerosis (MS). It ranges from 0 to 10, with 0 being normal and 10 representing death due to MS.',
    'education': 'Highest level of formal education completed by participant',
    'ethnicity': 'What is the participants ethincity',
    'height': 'Participant height measurement in centimeters',
    'manic_depression_bipolar': 'Does participant have manic_depression_bipolar or not',
    'ms_family': 'Participant number of family member(s) with MS',
    'MSSS': 'The MSSS (Multiple Sclerosis Severity Score) is a tool used in multiple sclerosis (MS) to assess disease severity by combining disability (measured by the EDSS) with disease duration. It provides a score that ranges from 0 to 10.',
    'nsaids': 'Did participant use non-steroidal anti-inflammatory drugs',
    'nsaids_specifics': 'Type of non-steroidal anti-inflammatory drugs used by participant',
    'occupation': 'Participant occupation',
    'ocd': 'Does participant have ocd or not',
    'ocps_y_n': 'Did participant take oral contraceptive pills or not',
    'otc_meds': 'Does participant take Over-the-counter medication',
    'otc_number': 'Total count of different Over-the-counte medications used',
    'pets': 'Does participant have pets or not',
    'postpartum_depression': 'Did female participant experience postpartum_depression or not',
    'probiotics': 'Has patient taken probiotics',
    'recreational_drug': 'Does participant take recreational drugs',
    'roommates': 'Participant roommates number',
    'rxmeds': 'Does participant take Prescription medication or not',
    'rxmeds_number': 'Participant total count of different prescription medications taken',
    'sex': 'What is the participants sex',
    'site': '1152 participants were recruited from seven sites (recruiting centers) located in San Francisco, Boston, New York, Pittsburgh, Buenos Aires, Edinburgh and San Sebastián',
    'smoke': 'Participant smoke history',
    'spms_year': 'Year of secondary progressive multiple sclerosis diagnosis',
    'treated': 'MS patient treatment status + their controls corresponding pair value. Patient can be treated or Untreated. If MS patient is treated, corresponding household member(control) would be treated_HHC.',
    'treatments_control': '(see the note on DMTs), MS patient treatment + their controls corresponding pair value. If patient was treated with Fingolimod, control value would be control_Fingolimod',
    'type2diabetes': 'Does participant have type2diabetes or not',
    'weight': 'What is the participants weight in kg',
    'which_ocp': 'Specific oral contraceptive pill(s) taken by participant',
    'year_of_onset': 'Year when participant was diagnosed with MS',

    'Alcohol % of cals (%)': 'FFQ calculation over last 6-12 months',
    'Beta-carotene (mcg)': 'FFQ calculation over last 6-12 months',
    'Bread, pasta, rice (1)': 'FFQ calculation over last 6-12 months',
    'Calcium (mg)': 'FFQ calculation over last 6-12 months',    
    'Calories (Kcal)': 'FFQ calculation over last 6-12 months',
    'Carbohydrate (g)': 'FFQ calculation over last 6-12 months',
    'Carbohydrate (g) as % of cals': 'FFQ calculation over last 6-12 months',
    'Cholestrol (mg)': 'FFQ calculation over last 6-12 months',
    'Dietary Fiber(g)': 'FFQ calculation over last 6-12 months',      
    'Fat (g)': 'FFQ calculation over last 6-12 months',
    'Fat (g) as % of cals': 'FFQ calculation over last 6-12 months',
    'Folate (mcg)': 'FFQ calculation over last 6-12 months',
    'Fruits, fruit juices (cups)': 'FFQ calculation over last 6-12 months',
    'Good oils, in foods ("teaspoons")': 'FFQ calculation over last 6-12 months',
    'household': 'FFQ calculation over last 6-12 months',
    'Iron (mg)': 'FFQ calculation over last 6-12 months',
    'Magnesium (mg)': 'FFQ calculation over last 6-12 months',
    'Meat, eggs, or beans (1)': 'FFQ calculation over last 6-12 months',
    'Milk, cheese, yogurt (cups)': 'FFQ calculation over last 6-12 months',
    'Monounsaturated fat (g)': 'FFQ calculation over last 6-12 monthss',
    'Niacin (mg)': 'FFQ calculation over last 6-12 months',
    'Polyunsaturated fat (g)': 'FFQ calculation over last 6-12 monthss',
    'Potassium (mg)': 'FFQ calculation over last 6-12 monthse',
    'Protein (g)': 'FFQ calculation over last 6-12 monthss',
    'Protein (g) as % of cals': 'FFQ calculation over last 6-12 months',
    'Saturated fat (g)': 'FFQ calculation over last 6-12 months',
    'Saturated fat (g) as % of cals': 'FFQ calculation over last 6-12 months',
    'Sodium (salt) (mg)': 'FFQ calculation over last 6-12 months',
    'Sweets % of cals (%)': 'FFQ calculation over last 6-12 months',
    'Vegetables group (cups)': 'FFQ calculation over last 6-12 months',
    'Vitamdietpairsumin A (RAE)': 'FFQ calculation over last 6-12 months',
    'Vitamin B6 (mg)': 'FFQ calculation over last 6-12 months',
    'Vitamin C (mg)': 'FFQ calculation over last 6-12 months',
    'vitamin D (IU)': 'FFQ calculation over last 6-12 months',
    'Vitamin E (mg)': 'FFQ calculation over last 6-12 months',
    'Whole grains (1)': 'FFQ calculation over last 6-12 months',
    'without potatoes (cups)': 'FFQ calculation over last 6-12 months',
    'Zinc (mg)': 'FFQ calculation over last 6-12 months'
}

# Sheet description
SHEET_DESCRIPTIONS = {
    'Dataset S1.2': 'Primary demographic and clinical characteristics dataset containing patient baseline information, medical history, and socioeconomic factors collected at study enrollment'
}